"""Initial migration

Revision ID: fb3aaaf58381
Revises: 
Create Date: 2025-12-13 17:48:52.561515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3aaaf58381'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postcode', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('organization_type', sa.String(length=100), nullable=True),
    sa.Column('parent_organization', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_code'), 'sites', ['code'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PUBLIC', 'REGISTERED', 'CLINICIAN', 'AUDIT_LEAD', 'QI_TEAM', 'GOVERNANCE', 'ADMIN', 'DPO', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_method', sa.Enum('NONE', 'TOTP', 'SMS', 'EMAIL', name='mfamethod'), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('nhs_login_id', sa.String(length=255), nullable=True),
    sa.Column('last_ig_training', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nhs_login_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('contains_pii', sa.Boolean(), nullable=False),
    sa.Column('records_accessed', sa.Integer(), nullable=True),
    sa.Column('justification', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('audits',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('clinical_domain', sa.String(length=100), nullable=False),
    sa.Column('population', sa.Text(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'UNDER_REVIEW', 'APPROVED', 'ACTIVE', 'PAUSED', 'CLOSED', 'ARCHIVED', name='auditstatus'), nullable=False),
    sa.Column('governance_body', sa.String(length=255), nullable=True),
    sa.Column('ethical_approval_ref', sa.String(length=100), nullable=True),
    sa.Column('data_protection_level', sa.Enum('NO_PII', 'PSEUDONYMISED', 'PII_REQUIRED', name='dataprotectionlevel'), nullable=False),
    sa.Column('dpia_reference', sa.String(length=100), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('allow_duplicate_entries', sa.Boolean(), nullable=False),
    sa.Column('require_consent', sa.Boolean(), nullable=False),
    sa.Column('total_episodes', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_records',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('completed_date', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('certificate_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sites',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'site_id')
    )
    op.create_table('data_exports',
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('export_type', sa.String(length=50), nullable=False),
    sa.Column('records_count', sa.Integer(), nullable=False),
    sa.Column('contains_pii', sa.Boolean(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approved_by_id', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('download_url', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('last_downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dpias',
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('assessment_data', sa.JSON(), nullable=False),
    sa.Column('approved_by_id', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('dpo_reviewed', sa.Boolean(), nullable=False),
    sa.Column('dpo_comments', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionnaires',
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('methodological_quality_score', sa.Float(), nullable=True),
    sa.Column('analysability_score', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_episodes',
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('questionnaire_id', sa.String(length=36), nullable=False),
    sa.Column('questionnaire_version', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('submitted_by_id', sa.String(length=36), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('episode_code', sa.String(length=100), nullable=True),
    sa.Column('pseudonym', sa.String(length=64), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('consent_obtained', sa.Boolean(), nullable=True),
    sa.Column('consent_date', sa.DateTime(), nullable=True),
    sa.Column('responses', sa.JSON(), nullable=False),
    sa.Column('derived_metrics', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_episodes_audit_id'), 'audit_episodes', ['audit_id'], unique=False)
    op.create_index(op.f('ix_audit_episodes_pseudonym'), 'audit_episodes', ['pseudonym'], unique=False)
    op.create_index(op.f('ix_audit_episodes_site_id'), 'audit_episodes', ['site_id'], unique=False)
    op.create_table('questions',
    sa.Column('questionnaire_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('question_code', sa.String(length=50), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('CATEGORICAL_SINGLE', 'CATEGORICAL_MULTIPLE', 'ORDINAL', 'NUMERIC', 'DATE', 'TIME', 'DATETIME', 'TEXT_SHORT', 'TEXT_LONG', 'BOOLEAN', name='questiontype'), nullable=False),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('clinical_guidance', sa.Text(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('validation', sa.JSON(), nullable=True),
    sa.Column('conditional_logic', sa.JSON(), nullable=True),
    sa.Column('free_text_max_length', sa.Integer(), nullable=True),
    sa.Column('free_text_justification', sa.Text(), nullable=True),
    sa.Column('validated_instrument', sa.String(length=255), nullable=True),
    sa.Column('variable_name', sa.String(length=100), nullable=False),
    sa.Column('variable_type', sa.String(length=50), nullable=False),
    sa.Column('variable_description', sa.Text(), nullable=True),
    sa.Column('has_guidance_warning', sa.Boolean(), nullable=False),
    sa.Column('warning_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_index(op.f('ix_audit_episodes_site_id'), table_name='audit_episodes')
    op.drop_index(op.f('ix_audit_episodes_pseudonym'), table_name='audit_episodes')
    op.drop_index(op.f('ix_audit_episodes_audit_id'), table_name='audit_episodes')
    op.drop_table('audit_episodes')
    op.drop_table('questionnaires')
    op.drop_table('dpias')
    op.drop_table('data_exports')
    op.drop_table('user_sites')
    op.drop_table('training_records')
    op.drop_table('audits')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sites_code'), table_name='sites')
    op.drop_table('sites')
    # ### end Alembic commands ###
